### ISSUE TITLE
Support USA / NOAA Nautical Chart Tile Service

### ISSUE THREAD

**Issue by danielschudel** [viking-gps/viking#101]
The National Oceanic and Atmospheric Administration provides geo-referenced nautical charts via a tile service compatible with WMTS and TMS. Full details are here: [NOAA RNC Tile Service Info](https://tileservice.charts.noaa.gov/about.html#home)

Support as a map layer, via "Layers -> New Map Layer", would be beneficial.

**Comment by danielschudel** [comment]
After looking in src/map_ids.h and src/osm.c to be able to implement NOAA charts, I discovered data/maps.xml and ~/.viking/maps.xml.

A modified ~/.viking/maps.xml helps with my immediate needs:
```
dan@xps15:~/file/viking$ cat ~/.viking/maps.xml 
<objects>
  <object class="VikSlippyMapSource">
    <property name="name">NOAA Charts</property>
    <property name="label">NOAA Charts</property>
    <property name="url">https://tileservice.charts.noaa.gov/tiles/50000_1/%d/%d/%d.png</property>
    <property name="copyright">TBD</property>
    <property name="license">TBD</property>
    <property name="license-url">TBD</property>
    <property name="id">802</property>
  </object>
</objects>
```

I'll leave this request open for consideration for addition to data/maps.xml in the repo and source.

**Comment by rnorris** [comment]
A collection of map XML snippets is available in the project Wiki:

https://sourceforge.net/p/viking/wikiallura/Maps/

I've added your NOAA example.
