### ISSUE TITLE
Treat a latitude containing a comma as a Latitude Longitude pair when entering a Waypoint

### ISSUE THREAD

**Issue by JohnLines** [viking-gps/viking#106]
If waypoints are geing added manually, for example you know that at some point, such as an old fashioned paper diary you were in Berlin, and get find the location of Berlin by looking it up, you will know the position as 52.52, 13.405

Rather than the user having to split this, it would be useful the latitude contained a comma, to treat this as entering a latitude of 52.52 and a longitude of 13.405

**Comment by rnorris** [comment]
This should be straight forward to add.

NB FYI: As mentioned in the manual:
"One way to create new waypoints is to copy a latitude/longitude coordinate pair, such as the one shown on most geocaches, and paste it into an active TrackWaypoint layer. Viking can automatically recognize several variations of the lat/lon format."

Unfortunately if you paste text from a Web Browser it is internally in HTML format, and Viking may not understand that properly if it is not in UTF16 (possibly an older default whereas now it seems to be UTF8 - at least on my system). I'll fix this error.

Copying text from a terminal / plain text program like notepad / gedit should work.
