### ISSUE TITLE
Easier way to enter historical dates

### ISSUE THREAD

**Issue by JohnLines** [viking-gps/viking#107]
If using Viking to work with a historical voyage - for example Eric the Red's voyage to Greenland, it would be useful to have a way to enter dates in Waypoints which are a long way from the current date. Mostly a simple way to directly enter the Year would be useful. I note that the KML specification allows for Month, Day and time to be unspecified anyway

```
<TimeStamp>
  <when>1997</when>
</TimeStamp>

```

**Comment by rnorris** [comment]
I think adding a text entry line to the date/time dialog, which would try to interpet the free form text as https://en.wikipedia.org/wiki/ISO_8601 (as there are low level functions for that conversion) could be done.

This should allow entering just a plain Year value and getting something usable (presumably going to the 1st day of that year). Internally it will still be a full timestamp - year/month/day/hh:mm:ss.ss.
