### ISSUE TITLE
Please improve KML export of tracks

### ISSUE THREAD

**Issue by JohnLines** [viking-gps/viking#108]
I have been creating some historical maps using a combination of Viking and OpenSteetMap OSM plugin, which I describe at [https://blog.wp.paladyn.org/2020/10/10/making-historical-maps-for-wordpress-with-viking-and-osm-plugin/](https://blog.wp.paladyn.org/2020/10/10/making-historical-maps-for-wordpress-with-viking-and-osm-plugin/)

In the process I noticed that the KML export of tracks could be improved, as they were simply exported with a name of Path, whereas I had put descriptions and names of the tracks into Viking. I edited manually like
```
357,358c356
<           <name>Train Paris to Rome</name>
<           <description>Rail</description>
---
>           <name>Points</name>


```
Which resulted in a better description on the exported map.

In a more modern context annotating Tracks might help people doing, for example Triathlons who presumably want to distinguish the running, cycling and swimming stages

**Comment by rnorris** [comment]
Viking uses [GPSBabel](https://www.gpsbabel.org) to generate the KML export (via an internal temporary GPX file).

I've recently added some further KML controls:
[Additional KML Export controls](https://github.com/viking-gps/viking/commit/575c48ca48aa591aff1132a9e38afa6cbdc26b7a)
and 
[Allow specifying suboptions for GPSBabel export](https://github.com/viking-gps/viking/commit/e18b97e73778514957e28e8d19f83f40ceb738ce)

NB These are subsequent to the v1.8 release. Thus not formally available, unless you are able to build Viking from the source code.

However I don't think these address the underlying issues which I believe are in GPSBabel itself:

1. It automatically generates a KML LineString even when told to generate a Track (via the option 'track=1'); and there is no way to turn off this LineString generation.

2. The GPX Track name is output as a KML Folder name (this 'Folder' holds the LineStrings) and then the automatically generated KML LineString is called Path. This seems wrong to me.

3. Using GPX (gpsbabel-1.7)-> KML (gpsbabel-1.7)-> GPX seems to lose the GPX Track description field, despite trying various options.

NB2 The description is in the KML when using GPSBabel KML option 'track=1', this option is now the default used in Viking (but only from the changes noted above).

It may be prudent to take these issues directly up  with the GPSBabel community https://github.com/gpsbabel/gpsbabel

HTH

**Comment by JohnLines** [comment]
Thank you, I will, time permitting, create some test cases to feed into GPSBabel

**Comment by rnorris** [comment]
NB In my previous comment in point 1 I was mistaken; one can in fact suppress LineString generation by using the KML option of 'lines=0'

Further note regarding track descriptions, they are present in the KML output - albeit in an HTML table within an description tag.
