### ISSUE TITLE
Crash when uploading GPS trace to OSM

### ISSUE THREAD

**Issue by M-Reimer** [viking-gps/viking#115]
We already had this in #98 and now I have the same problem again.

Uploading a GPS trace seems to succeed but then Viking disappears and on console I have:

    free(): double free detected in tcache 2

**Comment by rnorris** [comment]
I can't readily reproduce this issue with the latest code.

Can you please confirm a few details please which can help in diagnosing the problem:

- That you using the latest code (v1.8 hasn't been updated to include the fix in #98)
- What style of OSM authentication is being used (OAuth or OSM Username+Password)?
- Is the track GPX v1.0 or v1.1?
- And finally, if the GPX Upload is made a publically viewable OSM Track - and if you don't mind - could you please provide a link to the sucessful upload.

**Comment by M-Reimer** [comment]
I'm using the latest release. Actually I expected that after 7 months the fix could have landed in a bugfix release so it actually is usable for the average user.

Any plans when a release could happen?

**Comment by rnorris** [comment]
@M-Reimer - Hopefully a new release will be done by the end of March.
