### ISSUE TITLE
Feature request: user-modifiable highlight colour

### ISSUE THREAD

**Issue by sandaihu** [viking-gps/viking#117]
Currently in `v1.8` the `View / Set Highlight Color` in default has an orange hue, which is generally difficult to spot and follow on the also yellow-orange coloured roads. Most of the map layers use this styling, OpenStreetMap, OpenTopoMap, etc.

Would it be possible to add a user-setting to save a different highlight colour?
I know that a modified colour is saved into the .VIK project files, but it would be nice to have a custom colour in default, without the need to change it in each project.

Thank you.

**Comment by rnorris** [comment]
Funny you should raise this; I was thinking the same thing about a month ago.

So I have already addressed this in the latest code. See this very recent commit:

https://github.com/viking-gps/viking/commit/4c81dcf2ffb5c6204c04165706b902a109d6669d

This option is in the Preferences->Startup and thus is available now if you compile from source, or in the next release which it coming soon...

**Comment by sandaihu** [comment]
Perfect, thanks, I was thinking about some blueish as it's on the other side of the colour wheel from the orange, but purple is even better since many labels are generally in blue.
