### ISSUE TITLE
make error for Viking 1.9 under Fedora 33

### ISSUE THREAD

**Issue by pfps** [viking-gps/viking#118]
I upgraded my viking clone from 1.8 to 1.9.

After installing json-glib-devel I am running into a error when making:

```
Making all in help
make[1]: Entering directory '/home/local/SoftwareDownloads/viking/help'
Makefile:634: *** missing separator.  Stop.
make[1]: Leaving directory '/home/local/SoftwareDownloads/viking/help'
make: *** [Makefile:460: all-recursive] Error 1
```

The line in question is:

```
@YELP_HELP_RULES@
```

Any ideas on what is going on?

**Comment by rnorris** [comment]
Ensure you have 'yelp-tools' installed and possibly 'libxslt-tools'
Also 'docbook-xsl' and/or 'yelp-xsl' might be useful.

I thought these were required previously on Fedora but possibly not.

There was a commit "port to yelp-tools",  
which removes the usage of deprecated gnome-doc-utils.

**Comment by pfps** [comment]
Installing `yelp-tools` did the trick.

So it appears that 1.9 adds the following dependencies on Fedora:  `json-glib-devel` and `yelp-tools`.  The first is checked in configure but the second is not.
