### ISSUE TITLE
libX11 not added to linking command fails the build

### ISSUE THREAD

**Issue by landryb** [viking-gps/viking#119]
code added in 6d3b09bba0 checks for `XSetErrorHandler` which is present in `libX11` but it's not added to the linker libs list, so linking fails:
```
-O2 -pipe  -L/usr/local/lib -o viking main.o icons/libicons.a libviking.a -L/usr/local/lib -pthread -lgthread-2.0 -lgdk_pixbuf-2.0 -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -L/usr/local/lib -Wl,-rpath-link,/usr/X11R6/lib -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl  -lexpat -L/usr/local/lib -lcurl  -lnettle -lsqlite3 -lmagic -lbz2 -lgps -lgexiv2 -lgeoclue-2 -lz -lm 
ld: error: undefined symbol: XSetErrorHandler
>>> referenced by logging.c:168
>>>               logging.o:(a_logging_init) in archive libviking.a
cc: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by landryb** [comment]
from my understanding there are two checks, first for X11.h, then for `XSetErrorHandler` in libX11.

on OpenBSD for some reason the first check succeeds but the second fails, but the code using `XSetErrorHandler` is within `HAVE_X11_XLIB_H` so enabled..

**Comment by landryb** [comment]
i have it working with env vars to make sure the two checks succeeds, but for correctness the usage of `XSetErrorHandler` should be within `HAVE_LIBX11` ?

**Comment by rnorris** [comment]
NB In commit:6d3b09bba03479d59aea6fad12a87565fdc211fa it was merely shifting the code around from file main.c --> logging.c
So the original changes date back to 2012 -> commits: fa3eb9d69122f8eab6b9a9ba5b5b11c9bd1dbf98 + 5cd09d5716cca058b8270f13678d9d37ce7ed4ab

However agreed that `XSetErrorHandler` should be within `HAVE_LIBX11`

@landryb Can you confirm if using `HAVE_LIBX11` around `XSetErrorHandler` that it builds correctly without the env var workaround?

**Comment by landryb** [comment]
well yes, it does build and is more logical...
