### ISSUE TITLE
Crash while trying to use route finding

### ISSUE THREAD

**Issue by breadcan** [viking-gps/viking#12]
When trying to use the route engine viking crashes after setting the second point.

Version=1
EventType=APPCRASH
EventTime=130999200627358172
ReportType=2
Consent=1
UploadTime=130999200628578299
ReportIdentifier=70da3329-d307-11e5-82b0-001a4d4b7393
IntegratorReportIdentifier=a33f9231-68d7-410d-9caa-ee87d0abaade
WOW64=1
NsAppName=viking.exe
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=viking.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=56780126
Sig[3].Name=Fault Module Name
Sig[3].Value=viking.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=56780126
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0006d2ed
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10586.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=bdcb
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=bdcb33e65a9843796b7ec31cc25bda3b
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=5d92
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=5d920bb21fab29e05a2da7b29a2acf50
UI[2]=C:\Program Files (x86)\Viking\viking.exe
UI[3]=viking.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files (x86)\Viking\viking.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\SYSTEM32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\system32\apphelp.dll
LoadedModule[5]=C:\WINDOWS\AppPatch\AcGenral.DLL
LoadedModule[6]=C:\WINDOWS\SYSTEM32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\SYSTEM32\sechost.dll
LoadedModule[8]=C:\WINDOWS\SYSTEM32\RPCRT4.dll
LoadedModule[9]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[10]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[11]=C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll
LoadedModule[12]=C:\WINDOWS\SYSTEM32\SHLWAPI.dll
LoadedModule[13]=C:\WINDOWS\SYSTEM32\combase.dll
LoadedModule[14]=C:\WINDOWS\SYSTEM32\GDI32.dll
LoadedModule[15]=C:\WINDOWS\SYSTEM32\USER32.dll
LoadedModule[16]=C:\WINDOWS\SYSTEM32\ole32.dll
LoadedModule[17]=C:\WINDOWS\SYSTEM32\OLEAUT32.dll
LoadedModule[18]=C:\WINDOWS\SYSTEM32\SHELL32.dll
LoadedModule[19]=C:\WINDOWS\SYSTEM32\cfgmgr32.dll
LoadedModule[20]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[21]=C:\WINDOWS\SYSTEM32\advapi32.dll
LoadedModule[22]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[23]=C:\WINDOWS\SYSTEM32\shcore.dll
LoadedModule[24]=C:\WINDOWS\SYSTEM32\powrprof.dll
LoadedModule[25]=C:\WINDOWS\SYSTEM32\profapi.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\UxTheme.dll
LoadedModule[27]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[28]=C:\WINDOWS\SYSTEM32\samcli.dll
LoadedModule[29]=C:\WINDOWS\SYSTEM32\MSACM32.dll
LoadedModule[30]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[31]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[32]=C:\WINDOWS\SYSTEM32\dwmapi.dll
LoadedModule[33]=C:\WINDOWS\SYSTEM32\urlmon.dll
LoadedModule[34]=C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
LoadedModule[35]=C:\WINDOWS\SYSTEM32\MPR.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[37]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[38]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[39]=C:\WINDOWS\AppPatch\AcLayers.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\SETUPAPI.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\sfc.dll
LoadedModule[42]=C:\WINDOWS\SYSTEM32\sfc_os.DLL
LoadedModule[43]=C:\WINDOWS\SYSTEM32\IMM32.DLL
LoadedModule[44]=C:\Program Files (x86)\Viking\libbz2-2.dll
LoadedModule[45]=C:\Program Files (x86)\Viking\libcairo-2.dll
LoadedModule[46]=C:\Program Files (x86)\Viking\libcurl.dll
LoadedModule[47]=C:\WINDOWS\SYSTEM32\wldap32.dll
LoadedModule[48]=C:\WINDOWS\SYSTEM32\WS2_32.dll
LoadedModule[49]=C:\Program Files (x86)\Viking\libexif-12.dll
LoadedModule[50]=C:\Program Files (x86)\Viking\libexpat-1.dll
LoadedModule[51]=C:\Program Files (x86)\Viking\libgdk-win32-2.0-0.dll
LoadedModule[52]=C:\Program Files (x86)\Viking\libgdk_pixbuf-2.0-0.dll
LoadedModule[53]=C:\Program Files (x86)\Viking\libgio-2.0-0.dll
LoadedModule[54]=C:\Program Files (x86)\Viking\libglib-2.0-0.dll
LoadedModule[55]=C:\Program Files (x86)\Viking\libgobject-2.0-0.dll
LoadedModule[56]=C:\Program Files (x86)\Viking\libgthread-2.0-0.dll
LoadedModule[57]=C:\Program Files (x86)\Viking\libgtk-win32-2.0-0.dll
LoadedModule[58]=C:\Program Files (x86)\Viking\intl.dll
LoadedModule[59]=C:\Program Files (x86)\Viking\magic1.dll
LoadedModule[60]=C:\Program Files (x86)\Viking\libpango-1.0-0.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\COMDLG32.DLL
LoadedModule[62]=C:\Program Files (x86)\Viking\zlib1.dll
LoadedModule[63]=C:\WINDOWS\SYSTEM32\FirewallAPI.dll
LoadedModule[64]=C:\Program Files (x86)\Viking\sqlite3.dll
LoadedModule[65]=C:\WINDOWS\SYSTEM32\NETAPI32.dll
LoadedModule[66]=C:\Program Files (x86)\Viking\libgcc_s_dw2-1.dll
LoadedModule[67]=C:\Program Files (x86)\Viking\libfontconfig-1.dll
LoadedModule[68]=C:\Program Files (x86)\Viking\freetype6.dll
LoadedModule[69]=C:\Program Files (x86)\Viking\libpng14-14.dll
LoadedModule[70]=C:\WINDOWS\SYSTEM32\MSIMG32.DLL
LoadedModule[71]=C:\Program Files (x86)\Viking\libidn-11.dll
LoadedModule[72]=C:\Program Files (x86)\Viking\LIBEAY32.dll
LoadedModule[73]=C:\Program Files (x86)\Viking\SSLEAY32.dll
LoadedModule[74]=C:\Program Files (x86)\Viking\libpangocairo-1.0-0.dll
LoadedModule[75]=C:\Program Files (x86)\Viking\libgmodule-2.0-0.dll
LoadedModule[76]=C:\WINDOWS\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.10586.20_none_22adb5eaa762c7fa\gdiplus.dll
LoadedModule[77]=C:\WINDOWS\SYSTEM32\DNSAPI.DLL
LoadedModule[78]=C:\WINDOWS\SYSTEM32\NSI.dll
LoadedModule[79]=C:\Program Files (x86)\Viking\regex2.dll
LoadedModule[80]=C:\Program Files (x86)\Viking\libatk-1.0-0.dll
LoadedModule[81]=C:\Program Files (x86)\Viking\libpangowin32-1.0-0.dll
LoadedModule[82]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.10586.0_none_811bc0006c44242b\COMCTL32.DLL
LoadedModule[83]=C:\Program Files (x86)\Viking\libpangoft2-1.0-0.dll
LoadedModule[84]=C:\WINDOWS\SYSTEM32\USP10.DLL
LoadedModule[85]=C:\WINDOWS\SYSTEM32\DAVHLPR.DLL
LoadedModule[86]=C:\WINDOWS\SYSTEM32\fwbase.dll
LoadedModule[87]=C:\WINDOWS\SYSTEM32\MSCTF.dll
LoadedModule[88]=C:\WINDOWS\SYSTEM32\secur32.dll
LoadedModule[89]=C:\Program Files (x86)\Viking\lib\gtk-2.0\2.10.0\engines\libwimp.dll
LoadedModule[90]=C:\WINDOWS\SYSTEM32\clbcatq.dll
LoadedModule[91]=C:\WINDOWS\system32\propsys.dll
LoadedModule[92]=C:\WINDOWS\SYSTEM32\mscms.dll
LoadedModule[93]=C:\WINDOWS\SYSTEM32\icm32.dll
LoadedModule[94]=C:\WINDOWS\system32\winhttp.dll
LoadedModule[95]=C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
LoadedModule[96]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[97]=C:\WINDOWS\system32\napinsp.dll
LoadedModule[98]=C:\WINDOWS\system32\pnrpnsp.dll
LoadedModule[99]=C:\WINDOWS\system32\NLAapi.dll
LoadedModule[100]=C:\WINDOWS\System32\mswsock.dll
LoadedModule[101]=C:\WINDOWS\System32\winrnr.dll
LoadedModule[102]=C:\WINDOWS\System32\fwpuclnt.dll
LoadedModule[103]=C:\Windows\System32\rasadhlp.dll
LoadedModule[104]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[105]=C:\WINDOWS\SYSTEM32\NETUTILS.DLL
LoadedModule[106]=C:\WINDOWS\SYSTEM32\wkscli.dll
LoadedModule[107]=C:\WINDOWS\SYSTEM32\srvcli.dll
LoadedModule[108]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[109]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[110]=C:\Windows\SYSTEM32\ActXPrxy.dll
LoadedModule[111]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.10586.0_none_d3c2e4e965da4528\comctl32.dll
LoadedModule[112]=C:\WINDOWS\SYSTEM32\MLANG.dll
LoadedModule[113]=C:\WINDOWS\SYSTEM32\WININET.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=viking.exe
AppPath=C:\Program Files (x86)\Viking\viking.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=9AB68C413397329F84E9D864CDB6CBB4

**Comment by rnorris** [comment]
Thanks for taking the time to report this.

This is known bug - some discussion about it is here: https://sourceforge.net/p/viking/discussion/general/thread/4608ef71/?limit=25#a586/0486

Hence a fix has been made to the codebase, but this is not available in any formal build release yet.
Commit SHA:ac82d3c537adb8003170a872deb1344996940419

**Comment by rnorris** [comment]
Included in Viking 1.7
