### ISSUE TITLE
Exporting PNG when resolution doesn't current view match produces unusable result

### ISSUE THREAD

**Issue by takeshitakenji** [viking-gps/viking#127]
When I tried to create an image with a zoom level of 8 meters per pixel when viewing at 128, 64, 32, and 16 meters per pixel, including clicking "Area in current viewable window" after selecting the zoom level in the dialog, I get results like the attached image.

It only started producing these unusable results in version 1.9, and worked fine in 1.8 and earlier.  This is with Arch Linux, kernel 5.12.1, GTK 3.24.29, and Cairo 1.17.4.
![map](https://user-images.githubusercontent.com/524793/119707399-f9394900-be0f-11eb-9dd2-3ccfb30d3902.png)

**Comment by rnorris** [comment]
Thank you for taking the time to report this, but this has already been raised as #122 - being an issue with the GTK3 build.

So the current best options are to either update to the latest repository code or use the GTK2 build.
