### ISSUE TITLE
Build error in compression.c, v1.9

### ISSUE THREAD

**Issue by sandaihu** [viking-gps/viking#131]
Building `compression.c` throws the following error and fails the `make`:
>compression.c: In function ‘uncompress_load_zip_file’:
compression.c:169:11: error: ‘zip_filename’ undeclared (first use in this function); did you mean ‘filename’?
  169 |  g_free ( zip_filename );
      |           ^~~~~~~~~~~~
      |           filename
compression.c:169:11: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [Makefile:1083: compression.o] Error 1
make[3]: Leaving directory '/tmp/viking-master/src'
make[2]: *** [Makefile:1142: all-recursive] Error 1
make[2]: Leaving directory '/tmp/viking-master/src'
make[1]: *** [Makefile:805: all] Error 2
make[1]: Leaving directory '/tmp/viking-master/src'
make: *** [Makefile:463: all-recursive] Error 1

I'm not sure if this is the proper fix, but per the error message, if you change `zip_filename` to `filename`, then `make` finishes properly. Not tested if the compression functionality still works as expected.

Strangely I ran a build of this same v1.9 version about a month ago and didn't run into this problem; maybe that gcc version took this undeclared variable only as warning and still passed, but now it's considered as an error.

**Comment by rnorris** [comment]
It appears you are running the build __without__ (de)compression enabled. (i.e. the build option `--disable-zip` has been applied - and in this case opening GPX files within .zip files would not be available).
Unfortunately it appears I broke this build variant - even if it should be covered by the automatic build CI tests.
Perhaps as you suggest a differing gcc version detects this better.

The correct fix is to move the `#endif` on line 168 to be after the use of the `zip_filename` variable.
