### ISSUE TITLE
Support for geo: uri

### ISSUE THREAD

**Issue by tbruckmaier** [viking-gps/viking#134]
It would be nice if viking could handle `geo:` uris, like `viking "geo:37.786971,-122.399677"` (that would be the same as `viking --latitude 37.786971 --longitude -122.399677`)

Geo URIs normally consist just of latitude/longitude, but may have additional parameters as suffix, whole specification is here: https://geouri.org/ (RFC is linked)

As a workaround, I created a quick&dirty desktop file, which I set as default for geo urls:
```sh
$ cat ~/.local/share/applications/geo-protocol.desktop 
[Desktop Entry]
Name=open geo url with viking
# convert "geo:37.786971,-122.399677?z=16" to "--latitude 37.786971 --longitude -122.399677"
Exec=sh -c "viking $(echo %u | sed 's/geo:\s*\([0-9]\+\(\.[0-9]*\)\?\)\s*,\s*\([0-9]\+\(\.[0-9]*\)\?\).*/--latitude \1 --longitude \3/')"
Type=Application
Terminal=false
MimeType=x-scheme-handler/geo;
$ sudo update-desktop-database
$ xdg-mime default geo-protocol.desktop x-scheme-handler/geo
```

Now, `xdg-open "geo:37.786971,-122.399677"` or clicking a geo uri in the browser opens viking

**Comment by rnorris** [comment]
Agreed.

I have some provisionally working code and will seek to update the repository shortly.
