### ISSUE TITLE
Feature request: Modifier key to suspend route finder

### ISSUE THREAD

**Issue by roooots** [viking-gps/viking#135]
Hi,

I think the router finder function is one of the most helpful tools in viking and I use it quite often to plan longer outings on trails with lots of small-scale variations. However, it frequently happens that the route finding backend/provider just can't find any reasonable connection between the current and the next desired route point. This means finishing the current route, manually extending the route across that section, finishing it, continuing route finding with a new route and later appending these routes. In certain areas, this can become somewhat tedious. 

In these cases, a modifier key like CTRL, ALT or SHIFT which suspends the routing queries and allows left-clicks to just place regular route points for as long as the modifier is pressed without having to finish the current route, would be very welcome.

So the desired behaviour would be:
1. Start a route using the route finder tool and click along
2. When encountering a problematic section, press and hold the modifier key and use regular left-clicks to continue across that section
3. When on "safe grounds" again, release the modifier key and continue the route with active route finding functionality.

Is is feasible to implement such function without significant rewriting of code?

Cheers,
r.

**Comment by rnorris** [comment]
"This means finishing the current route, manually extending the route across that section, finishing it, continuing route finding with a new route and later appending these routes. In certain areas, this can become somewhat tedious."

You do not need to __finish__ the route - you can simply switch between the manual Route tool and the Router Finder tool at any time - (either by clicking on the button in the toolbar or the keyboard shortcuts) and carry on adding points in a manner that is in accordance to the active tool.

Thus I don't believe such a feature as you propose is necessary.

HTH.

**Comment by roooots** [comment]
Wow - that's great, I really did not try this yet. So yes, this is pretty much what I was looking for. Thanks for the pointer!
