### ISSUE TITLE
Invalid GPX created

### ISSUE THREAD

**Issue by daniel-molina** [viking-gps/viking#137]
I am using viking 1.9. Exporting certain imported GPX tracks (even full ones) as GPX creates an invalid XML file according to a XML validator. Uploading the track to OSM fails too (probably because of the same reason).

I reproduce this issue importing GPX files generated by FitoTrack 12.1, but not with some others from different sources. I attach one example. For this one the validator just report a warning (not an error) and viking exports a GPX with an error. Note that I changed the extension from gpx to txt so that github would allow me to attach it.

[gpx_input.txt](https://github.com/viking-gps/viking/files/7130219/gpx_input.txt)

**Comment by rnorris** [comment]
@daniel-molina Is the attached track the output from FitoTrack or from Viking's export?
If the latter, then can you upload the original FitoTrack file please.

Also can you also describe which XML validator program/service was used please.

**Comment by daniel-molina** [comment]
I have not much experience on GPX, but xmlvalidation.com firstly reports for my previously attached FitoTrack GPX to have a warning. However, later it refers to it as an error. In any case, it is just what is referred in the FitoTrack issue that you mentioned.

```
A warning has been found!
[...]
Errors in the XML document:
	2:	304	schema_reference.4: Failed to read schema document 'http://www.topografix.com/GPX/1/1/gpx.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
```

I can also say that OSM accepts FitoTrack GPX files as input (it is not possible to do it from viking but directly from OSM web interface). Personally, it would be nice for me if viking could manage those files :D, but I understand that is FitoTrack issue after all.

**Comment by daniel-molina** [comment]
I tried an alternative to FitoTrack, the Trip Recording plugin of OsmAnd~. After exporting the GPX with viking new errors appear. The original GPX is attached in a [OsmAnd issue](https://github.com/osmandapp/OsmAnd/issues/12789) I reported, currently being discussed there if the trace is invalid or not. Output from viking for that input is attached here.

[BusGranadaZubia_viking.txt](https://github.com/viking-gps/viking/files/7186584/BusGranadaZubia_viking.txt)

**Comment by rnorris** [comment]
I think ATM if one uses the Track-->Export Track as GPX..., then Viking writes it's own GPX header - which may not be consistent with the trackpoint extensions being used (which in the the above case has _osmand:speed_ value extensions).
And so may fail 'external schema' validation.

NB When one uses the Layer-->Export Layer-->Export as GPX... then the input GPX headers are retained properly and the so the exported file should be consistent.
