### ISSUE TITLE
Hide calendar, Goto, and Stats from the sidepanel

### ISSUE THREAD

**Issue by r1de** [viking-gps/viking#146]
I am trying to minimize the viking UI down to things I will only need, I use Viking with a dashboard mounted RasPi in our truck.

I cannot get the calendar and other things at the bottom of the sidepanel to be hidden.
tried to use View -> Show and uncheck them, which does not save, when I open the window they are back.

also tried going into viking.ini and setting `window_sidepanel_calendar=false` but that doesn't seem to do it either?

Any tips?

Thank you in advance. :smile:

**Comment by rnorris** [comment]
Hmm, this should be working (it does for me).

What version of Viking are you using?

Also check if the settings are saved in ~/.viking/ or ~/.config/viking/
The latest versions (IIRC 1.9+) now use ~/.config/viking/, but if there is the old directory ~/.viking/ it will continue to use that (but the program itself should still be updating/rereading its own changes correctly).

**Comment by r1de** [comment]
Viking 1.10
Just compiled it yesterday on a fresh x64 raspberry pi install.
I only have the ~/.config/viking directory.
Perhaps one of the --disable-xxxx flags I used broke it?

**Comment by rnorris** [comment]
Some quick things to note:

1. I couldn't actually get it to compile with the options you set. I think the '--disable-geonames' is currently broken (only by about 9 years if my initial invagination is correct!!). I will fix this imminently.
2. There seems a separate fault in the View -> "Set Background Color". I'll investigate this shortly.

I guess these aren't options/features people generally use much.

Anyway more importantly, the View->Show settings are only kept if the `Edit -> Preferences -> Startup`  `Restore Window Setup` is enabled. (this is off by default). This should address your issue.

**Comment by rnorris** [comment]
Some code updates have been uploaded - addresses the points above.

NB For View -> "Set Background Color" - this setting (for historical reasons) is only saved as part of the Viking files.
And thus is only restored when you open the .vik file you have saved.
NB2 If you really want the Background color set every time you run Viking, look into the Preferences --> Startup --> Startup Method: --> "Specified File" and then set the Startup File option to your chosen .vik File.

**Comment by r1de** [comment]
`Edit -> Prefs -> Startup` `Restore Window Setup` was the trick! Thank you very much. I've been fighting with trying to hide that sidebar stuff for a _long_ time. :+1: 

Did not know "geonames" was broken, I try to disable all of that stuff since this system spends most of it's life offline.
It's mostly for keeping track of where we've been on our adventures and giving us reliable offline mapping (with topographic maps even!!).

I dont really use the background color setting, I just used that to try and get _any_ of my settings to stick in viking, still, glad you got the background color setting fixed. :smile: 

This issue can be closed, as it is resolved.
Thank you again!

**Comment by jidanni** [comment]
Fresh 1.10 install. Calendar insists on being there each startup.
