### ISSUE TITLE
Keyboard shortcuts for editing trackpoints

### ISSUE THREAD

**Issue by rskrakowski1** [viking-gps/viking#150]
If this is possible I haven't found a way of doing it.....

When I am editing track points, I would love to be able to simply use the arrows instead of clicking 'Foward' and 'Back' in the popup box, and also if possible, being able to delete track points by using the keyboard as well.

**Comment by rnorris** [comment]
NB Probably better just to use the default 'Select' mode.
Then when a trackpoint is selected, the keyboard left/right arrows goes to the previous/next trackpoint respectively.
Ctrl+D will remove the selected trackpoint.
