### ISSUE TITLE
Panning the map while in 'edit trackpoint' mode

### ISSUE THREAD

**Issue by rskrakowski1** [viking-gps/viking#151]
When I am in 'edit trackpoint' mode and want to pan the map, I have to click the 'pan' button

![image](https://user-images.githubusercontent.com/64157903/167498166-62ba330d-ebdf-44a5-9d56-2db018c6ee23.png)

Is it possible for this to be removed and panning to be possible without having to enter 'pan' mode?

**Comment by rnorris** [comment]
NB Panning is always available by holding down the middle mouse button and then moving the mouse.
This is irrespective of the tool mode in operation.
