### ISSUE TITLE
Routing is broken with default routing.xml, because stratoserver.net is down

### ISSUE THREAD

**Issue by codesoap** [viking-gps/viking#153]
The current `routing.xml` file contains two entries using h2096617.stratoserver.net. This server seems to be down:

```
$ curl h2096617.stratoserver.net
curl: (6) Could not resolve host: h2096617.stratoserver.net
```

**Comment by rnorris** [comment]
Apologies for taking somewhat of a long time to respond!
Thanks for the notification.

You can replace the old brouter address instances in your copies of `routing.xml` with the latest value:

 http://h2096617.stratoserver.net --> https://brouter.de
