### ISSUE TITLE
Feature request: draggable Create waypoint tool

### ISSUE THREAD

**Issue by sandaihu** [viking-gps/viking#156]
Would it be possible to rig a dragging event on the `Create waypoint` tool to drag the map? I often add waypoints, then move around on the map to add a new at a different location. Now first I need to change to some other tool like `Pan` or `Select`, as a single click already activates the waypoint adding dialog -move around - then again the `Create waypoint`.
Thank you.

**Comment by rnorris** [comment]
You should be able to use the middle mouse button to drag the map around, regardless of the tool selected (including the Create Waypoint one).

HTH.

**Comment by sandaihu** [comment]
Gotcha, thanks, the middleclick does the trick.
