### ISSUE TITLE
org.gnome.Platform 41 is end-of-life

### ISSUE THREAD

**Issue by KD0DOS** [viking-gps/viking#165]
Info: org.gnome.Platform//41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.viking.Viking

**Comment by rnorris** [comment]
The Flatpak file in the Viking repository does not use the GNOME runtime (it uses the KDE Runtime).

Note that the Flatpak configuration for the release hosted on https://flatbug.org is in the separate repository:

https://github.com/flathub/org.viking.Viking
