### ISSUE TITLE
Viking 10.1 can't find libmapnik.so.3.0

### ISSUE THREAD

**Issue by theHedster** [viking-gps/viking#167]
Ubuntu 22.0.4
Mapnik
installation
share object file

I have installed Viking GPS using the install.sh script in the BZ2 archive extracted to my Ubuntu 22.0.4 laptop. When I try to launch Viking I get the error message  

`$ viking
viking: error while loading shared libraries: libmapnik.so.3.0: cannot open shared object file: No such file or directory`

I can't find this file anywhere. Can anybody assist as surely somebody has had the same issue?

**Comment by sandaihu** [comment]
These are the development packages you'll need to install to build viking on Debian/Ubuntu:
>   gtk-doc-tools                                                                 
  libjson-glib-dev                                                              
  libgeoclue-2-dev                                                              
  libgexiv2-dev                                                                 
  liboauth-dev                                                                  
  libgps-dev                                                                    
  libmagic-dev                                                                  
  libmapnik-dev                                                                                                                                                
  libnova-dev                                                                   
  libsqlite3-dev                                                                
  nettle-dev

It seems you're missing the `libmapnik-dev`.
