### ISSUE TITLE
Feature request - ability to paste file path

### ISSUE THREAD

**Issue by jackanory101** [viking-gps/viking#169]
I really appreciate Viking, it's great. However there's one thing that irritates me - opening/saving files.

In every other app I use I am able to paste the path/filename into dialog boxes for opening and saving files. If I want to open a particular file in  a piece of software I simply copy the file path in file manager (I use Total Commander but I could also do this simply in Explorer), then switch back to the Open dialog, and paste the path in there. 

Viking does not allow this. Very often I find myself clicking endlessly to navigate to the file I want to open, or to the directory where I want to save/export a file. This seems unnecessarily sadistic on part of developers. 

Please allow users to paste file path into Open and Save dialogs!

**Comment by Shura0** [comment]
Doesn't Ctrl+L work in file dialog?

**Comment by jackanory101** [comment]
Great! that works. Did I miss something in the documentation? A quick search suggests `<C-l>` is a GTK+ file selection dialog hotkey.

**Comment by rnorris** [comment]
I too find the GTK3 file dialogs less useful, but that's the joy of using frameworks where such detail is beyond one's control.

It can be helpful to think/remember that the Ctrl + 'L' is L for Location.
