### ISSUE TITLE
Help Missing

### ISSUE THREAD

**Issue by caltrop2075** [viking-gps/viking#172]
Viking 1.7

installed from Ubuntu/Mint repository
which is severly outdated

help is missing - where is it

F1 - HELP
Document Not Found
The URI ‘ghelp:viking’ does not point to a valid page.

yeah... I do NOT do FlatPak, Snap, or ApImage
I abhor that stuff

your PPA does not suport Focal
I've been geting that a lot

        OS   Linux Mint 20.1 x86_64
      Host   Latitude E5570
    Kernel   Linux 5.4.0-153-generic
     Shell   bash 5.0.17
Resolution   1366x768
        DE   MATE

**Comment by rnorris** [comment]
I'm afraid that appears to be an issue with the package manager for your system.

A copy of the latest help manual (for v1.10) in PDF form is here:
 https://sourceforge.net/projects/viking/files/viking.pdf/download

An online version is here - albeit it seems to be for v1.9
 https://sourceforge.net/p/viking/wikiallura/MasterHelp/

Alternatively, especially if you don't want to use Flatpak (of which there is one for [Viking](https://flathub.org/apps/org.viking.Viking) for v1.10) - then as an Open Source project - there is always the compile from source option - see the advice [here](https://sourceforge.net/p/viking/wikiallura/Source_code/) - (or even just use the source release and go to the `help/C` directory within it and run the program `yelp` on the index.docbook (or if you go back to the equivalent v1.7 release - IIRC the file was previously named viking.xml) - as that is effectively what F1 does (or should be doing on the installed system).

Lastly if there is a possibility that I could try and reconstruct the older help PDFs and put them in the SourceForge downloads area.

**Comment by rnorris** [comment]
Older help files (including the PDF for Viking v1.7)  have been added to the Files list on SourceForge:

https://sourceforge.net/projects/viking/files/

Further note older PDFs should be available in the Release section here on GitHub:

https://github.com/viking-gps/viking/releases

Although it appears I forgot to include the PDF in the v1.7 assets.

**Comment by rnorris** [comment]
Sorry I don't think that's possible with the PDF.

For Linux, the Help is meant to open the (should be) installed help file(s) which are in docbook .xml format - located in at least for Debian /usr/share/help/C/viking/ and are then opened by the system help viewer - via that "ghelp:viking" reference - normally `yelp`. Yelp does not handle PDF files; nor is there a way to configure that URI.

Whereas for the Windows version of Viking, the Help menu opens the PDF file (which IIRC is mainly why these PDFs are generated).

I suppose the other option is to download the Viking 1.7 source release, extract the files and manually copy the help files into the right system location.
