### ISSUE TITLE
trying to use on unbuntu 22.04 or ubuntu 23.04

### ISSUE THREAD

**Issue by lebrun35** [viking-gps/viking#179]
[Heloo,](url)
I get vicking-gps from github but when I try to generate the executable, I get errors:

am__fastdepCC_FALSE=''
am__fastdepCC_TRUE='#'
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE='#'
am__include='#'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build='x86_64-pc-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='pc'
check-help:
check: check-help
clean-help:
datadir='${datarootdir}'
datarootdir='${prefix}/share'
distdir-help-files: $(_HELP_LC_FILES)
distdir: distdir-help-files
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-pc-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='pc'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install-data-am: $(if $(HELP_ID),install-help)
install-help: $(_HELP_LC_FILES)
install_sh='${SHELL} /home/arnaud/viking/install-sh'
intltool__v_merge_options_0='-q'
intltool__v_merge_options_='$(intltool__v_merge_options_$(AM_DEFAULT_VERBOSITY))'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='/usr/local/share/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='/usr/bin/mkdir -p'
mostlyclean-am: $(if $(HELP_ID),clean-help)
oldincludedir='/usr/include'
pdfdir='${docdir}'
pot: $(_HELP_POTFILE)
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
repo: $(_HELP_POTFILE)
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target='x86_64-pc-linux-gnu'
target_alias=''
target_cpu='x86_64'
target_os='linux-gnu'
target_vendor='pc'
uninstall-am: $(if $(HELP_ID),uninstall-help)
uninstall-help:

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "viking"
#define PACKAGE_TARNAME "viking"
#define PACKAGE_VERSION "1.10"
#define PACKAGE_STRING "viking 1.10"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL "http://viking.sf.net/"
#define PACKAGE "viking"
#define VERSION "1.10"
#define GETTEXT_PACKAGE "viking"
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_LOCALE_H 1
#define HAVE_LC_MESSAGES 1
#define HAVE_BIND_TEXTDOMAIN_CODESET 1
#define HAVE_GETTEXT 1
#define HAVE_DCGETTEXT 1
#define ENABLE_NLS 1
#define LOCALEDIR "/usr/local/share/locale"
#define ENABLE_NLS 1
#define HAVE_GETTEXT 1
#define HAVE_DCGETTEXT 1
#define HAVE_MALLOC_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_UTIME_H 1
#define HAVE_X11_XLIB_H 1
#define HAVE_MEMSET 1
#define HAVE_MKDTEMP 1
#define HAVE_REALPATH 1
#define HAVE_STRCASECMP 1
#define HAVE_STRCHR 1
#define HAVE_STRNCASECMP 1
#define HAVE_STRTOL 1
#define HAVE_STRTOUL 1
#define HAVE_STRPTIME 1
#define HAVE_FMEMOPEN 1
#define HAVE_LIBM 1
#define HAVE_LIBZ 1
#define HAVE_LIBX11 1
#define HAVE_EXPAT_H 1
#define HAVE_LIBCURL 1
#define LIBCURL_FEATURE_ASYNCHDNS 1
#define LIBCURL_FEATURE_GSS_API 1
#define LIBCURL_FEATURE_HSTS 1
#define LIBCURL_FEATURE_HTTP2 1
#define LIBCURL_FEATURE_HTTPS_PROXY 1
#define LIBCURL_FEATURE_IDN 1
#define LIBCURL_FEATURE_IPV6 1
#define LIBCURL_FEATURE_KERBEROS 1
#define LIBCURL_FEATURE_LARGEFILE 1
#define LIBCURL_FEATURE_NTLM 1
#define LIBCURL_FEATURE_NTLM_WB 1
#define LIBCURL_FEATURE_PSL 1
#define LIBCURL_FEATURE_SPNEGO 1
#define LIBCURL_FEATURE_SSL 1
#define LIBCURL_FEATURE_TLS_SRP 1
#define LIBCURL_FEATURE_UNIXSOCKETS 1
#define LIBCURL_FEATURE_ALT_SVC 1
#define LIBCURL_FEATURE_BROTLI 1
#define LIBCURL_FEATURE_LIBZ 1
#define LIBCURL_FEATURE_ZSTD 1
#define LIBCURL_PROTOCOL_DICT 1
#define LIBCURL_PROTOCOL_FILE 1
#define LIBCURL_PROTOCOL_FTP 1
#define LIBCURL_PROTOCOL_FTPS 1
#define LIBCURL_PROTOCOL_GOPHER 1
#define LIBCURL_PROTOCOL_GOPHERS 1
#define LIBCURL_PROTOCOL_HTTP 1
#define LIBCURL_PROTOCOL_HTTPS 1
#define LIBCURL_PROTOCOL_IMAP 1
#define LIBCURL_PROTOCOL_IMAPS 1
#define LIBCURL_PROTOCOL_LDAP 1
#define LIBCURL_PROTOCOL_LDAPS 1
#define LIBCURL_PROTOCOL_MQTT 1
#define LIBCURL_PROTOCOL_POP3 1
#define LIBCURL_PROTOCOL_POP3S 1
#define LIBCURL_PROTOCOL_RTMP 1
#define LIBCURL_PROTOCOL_RTSP 1
#define LIBCURL_PROTOCOL_SCP 1
#define LIBCURL_PROTOCOL_SFTP 1
#define LIBCURL_PROTOCOL_SMB 1
#define LIBCURL_PROTOCOL_SMBS 1
#define LIBCURL_PROTOCOL_SMTP 1
#define LIBCURL_PROTOCOL_SMTPS 1
#define LIBCURL_PROTOCOL_TELNET 1
#define LIBCURL_PROTOCOL_TFTP 1
#define VIK_CONFIG_BING /**/
#define VIK_CONFIG_GOOGLE /**/
#define VIK_CONFIG_OPENSTREETMAP /**/
#define VIK_CONFIG_BLUEMARBLE /**/
#define VIK_CONFIG_GEONAMES /**/
#define HAVE_LIBGEOCLUE_2 1
#define HAVE_LIBGEXIV2 1
#define VIK_CONFIG_GEOTAG /**/
#define HAVE_OAUTH_H 1
#define HAVE_LIBOAUTH 1
#define HAVE_GPS_H 1
#define HAVE_LIBGPS 1
#define VIK_CONFIG_REALTIME_GPS_TRACKING /**/
#define HAVE_BZLIB_H 1
#define HAVE_LIBBZ2 1
#define HAVE_MAGIC_H 1
#define HAVE_LIBMAGIC 1
#define HAVE_SQLITE3_H 1
#define HAVE_LIBSQLITE3 1
#define HAVE_ZIP_H 1
#define HAVE_LIBZIP 1
#define HAVE_LIBNETTLE 1
#define HAVE_LIBNOVA_LIBNOVA_H 1
#define HAVE_LIBNOVA 1

configure: exit 1

**Comment by rnorris** [comment]
I think you need to run `./autogen.sh` first before `./configure`

Please refer to the `README.md` and the [wiki](https://sourceforge.net/p/viking/wikiallura/Source_code/) for further details for compiling from source.

HTH.
