### ISSUE TITLE
mbtiles - Unrecognised file format

### ISSUE THREAD

**Issue by DF-OMNIUS** [viking-gps/viking#187]
Hi, 

Having a bit of trouble getting offline maps working!

Running Viking v1.10 on Windows 10 OS. 

I need an offline source for OSM covering the UK. I've downloaded several OSM-Mbtiles from places like geofabrik and keep getting the following error in the log:

get_pixbuf_sql_exec: Unrecognised image file format

Ideally I'd like to use mbtile files but if there's an alternative to getting an offline copy of OSM for the UK then I'll take it!

**Comment by rnorris** [comment]
Note that Viking only supports **raster** MBTiles - i.e. **not** vector MBTIles.
I don't think the GUI nor the (current) Help information makes this explicitly clear. I will amend this in due course.

I'm having trouble finding any MBTiles downloads from geofabrik - but I suspect it would be some kind of vector format.

Supporting vector map drawing (either from Garmin .img file - is a long time open request -  https://sourceforge.net/p/viking/feature-requests/147) or potentially OSM .pbf. But this is a significant change to Viking and unlikely to be done. 

A raster sample is linked below:

https://github.com/klokantech/vector-tiles-sample/releases/download/v1.0/countries-raster.mbtiles

I don't know of any sources offering raster MBTiles of the UK.

NB Viking source code (in this repo - not included in the Windows install) has a python script tool to convert between Viking's cache files and an MBTile file (see `tools/viking-cache.py`)

**Comment by rnorris** [comment]
To be more specific (depending on the MBTiles spec version) the file should state the tiles `format` contained in it.

https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md

I believe Viking can be updated to at least detect this and programmatically say if the file selected is supported or not (i.e. not those of format = pdf).
