### ISSUE TITLE
KML styles ignored

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#191]
The KML style I used said lines should be red. However they're still blue.

[vikingColorOverride.kml.gz](https://github.com/viking-gps/viking/files/12567984/vikingColorOverride.kml.gz)

I see, viking has other uses for colors. But there should still be a way to say "hands off."

**Comment by rnorris** [comment]
Support for KML track colours was added in this commit:

https://github.com/viking-gps/viking/commit/8ce52ddc1a0a4391fed41e7b8daff8bc9b410743

However that is after the v1.10 release, so it is not yet included in any formal version yet.

Thanks for your sample .kml file. The colour seems to be working OK with the latest source code from the repository.

**Comment by rnorris** [comment]
Marked as closed.
Since Github doesn't have a 'pending fixed'/'fixed in repo but not in a release' style Issue statuses, I tend to close the issue if code has been updated - although it isn't in any formal release yet.
