### ISSUE TITLE
--map 0 to use no map

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#205]
If `--map 123` can be used to choose an initial map right from the command line,
then perhaps allow `--map 0` to mean "use no map this session."

**Comment by rnorris** [comment]
As per the help about the --map option:
"Specifying a value of 0 will use the map layer default."

In fact specifying '--map **-2**' (or indeed any other negative number, apart from '-1' ATM - I'll probably change this to allow -1 as well) - will do what you want.

I will add this explicitly to the documentation.
