### ISSUE TITLE
Use filename as title, better than nothing

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#207]
I do
- viking x.kmz &

then later
- viking y.kmz &

In the chromebook toolbar I tap the single viking icon and see
Viking
- Untitled - Viking
- Untitled - Viking

It would be better to see

Viking
- x.kmz - Viking
- y.kmz - Viking

Or
Viking
- x - Viking
- y - Viking

That way I could know which to tap to get which.

And if I instead did
viking x.kmz y.kmz &
viking z.kmz &

Then I should see
Viking
- x, y - Viking
- z    - Viking

or
Viking
- x.kmz y.kmz - Viking
- z.kmz - Viking

or
Viking
- x... - Viking
- z - Viking

**Comment by rnorris** [comment]
The Title displayed by Viking is the name of the Viking **Project** - AKA .vik files.

Individual other geodata file types (GPX, KML, etc...) are loaded into the Viking project, hence as you have not specified a Viking Project it remains 'Untitled'.

I understand your use case (and indeed the common simple case) of viewing individual other geodata file types.

I think a compromise would be (when no Viking Project is used) to show the filename - specifically when only one file is loaded - as the title in square brackets .e.g. **[filename.gpx]**.  If multiple files are loaded then it will return to the implicit project name i.e. Untitled - as multiple files will take up too much space.
