### ISSUE TITLE
Bad EOL on Windows causes errors when developing in container with VSCode

### ISSUE THREAD

**Issue by starnutoditopo** [viking-gps/viking#210]
Cloning the project on a Windows machine causes EOL to be \r\n. This prevents correct execution of shell scripts when developing in docker container with Visual Studio Code.

It is enough to add a `.gitattribute` file with the following content to solve the problem:

```
*.sh text eol=lf
```
or, at least, specify in the documentation to use the `--config core.autocrlf=false` flag when cloning the project:

```sh
git clone --config core.autocrlf=false https://github.com/viking-gps/viking
```

**Comment by rnorris** [comment]
Added a `.gitattribute` file.

**Comment by starnutoditopo** [comment]
Sorry (my mistake!), the filename should be `.gitattributes` (with final "s").
References: https://git-scm.com/docs/gitattributes
