### ISSUE TITLE
--open-as-new-layer-in-existing-session

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#211]
Maybe add a
`viking --open-as-new-layer-in-existing-session file.kml`
command line switch.

```
$ viking file1.kml &
$ viking --open-as-new-layer-in-existing-session file2.kml
```
would give the same results as
```
$ viking file1.kml file2.kml
```

**Comment by rnorris** [comment]
Implementation notes:
Probably can use the technique used by Geany.
I believe it uses an IPC socket to send commands (thus if an existing program is running it can be passed on to it).
Geany seems to complicate things by having Windows (and possibly Mac) support too - where the socket APsI are slightly different - which probably could be skipped as it's rather unlikely any one invokes desktop programs from the command line - but relatively common in Linux like land.

**Comment by jidanni** [comment]
Well chrome all puts them in the same instance.
Emacs all puts them in separate instances, unless one uses emacsclient -n.
In any case be sure to allow the user some choice.

**Comment by rnorris** [comment]
Can now use this to open in an existing session:
`./viking -r filename`
or
`./viking --running-instance filename`

**Comment by rnorris** [comment]
Hmm, oh dear this causes Viking to crash on start-up on Ubuntu systems (as per CI tests). Works fine on (latest) Debian at least as per my main development system.

Seems to be some oddity with the build system/versioning/includes on Ubuntu - so doesn't find the function g_unix_socket_address_new_with_type() (which AFAIK should be available) when compiling socket.c - yet then links the application together - and then instead crashes when used at runtime :(

I probably won't have time to resolve this in the next few days. So this is just a heads up message about the current state of play...

**Comment by rnorris** [comment]
If any one needs the fix to run it - add this line to the top of the **socket.c** flle:

`#include <gio/gunixsocketaddress.h>`

I won't be able to upload it to the source repository until back on a computer with appropriate access (about a weeks time).

**Comment by rnorris** [comment]
Finally!
