### ISSUE TITLE
Make help manual available outside of the program

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#218]
There is extensive help documentation, but the catch 22 is one needs to start Viking in order to access it.

Please also make an HTML or PDF version people can browse in comfort on the web.

OK I did
> xsltproc -o V.html /usr/share/xml/docbook/stylesheet/nwalsh/xhtml/docbook.xsl /usr/share/doc/HTML/en/viking/index.docbook

but it did make a lot of error messages.

Also images didn't get picked up, which actually highlights another problem,
there are many lines that just say
> This mode can be entered by clicking on the toolbar icon: [image]

Well, for web accessibility's sake also mention a little of which icon it is...

Anyway, still do make PDFs and HTMLs and put it on your website.

**Comment by rnorris** [comment]
PDFs (for the last three or four versions) are already available, either:

- https://sourceforge.net/projects/viking/files
- https://github.com/viking-gps/viking/releases

Unfortunately AFAIK I've not had the ability/access on SourceForge to upload raw HTML, hence a rather hacked up version is forced into a Wikified version:

- https://sourceforge.net/p/viking/wikiallura/MasterHelp/

But I've just realised there is scope in the minimal github site, so I've just added:

 - https://viking-gps.github.io/help/index.html

**Comment by rnorris** [comment]
NB Rather than using xsltproc, I use `dblatex` to produce the PDF - which as far as I can tell has no issues, like this:

    dblatex index.docbook -o viking.pdf
