### ISSUE TITLE
[Feature] Add capability to add a custom layer

### ISSUE THREAD

**Issue by starnutoditopo** [viking-gps/viking#230]
It would be handy to have the capability to define custom tile layers, perhaps by specifying a parametrized URL for a tile, such as `http://{s}.my.url/path/{z}/{x}/{y}.png?apiKey=1234abcd`

**Comment by rnorris** [comment]
You already can, although not the `{s}` part support currently. You have to manually hard-code that value - either 'a' or 'b' or 'c'.

See the Wiki - https://sourceforge.net/p/viking/wikiallura/Maps/ and the manual for Extending Viking - Map Sources
