### ISSUE TITLE
Allow to export the "Top Layer" via GPSbabel

### ISSUE THREAD

**Issue by M-Reimer** [viking-gps/viking#239]
I can export each individual layer using GPSbabel but a menu point to do this for the "Top Layer" is missing.

As Viking exports a temporary GPX to use GPSbabel, I guess it shouldn't be too difficult to add this as exporting the "Top Layer" to GPX is possible?

**Comment by rnorris** [comment]
For any Aggregate Layer, an export method is available, but easy to miss as it is further down in the menu structure.

Right click on the Agg Layer -> File -> Export as GPX...  - This will save to a single GPX file with all the layers merged together in it.

Note1: It will only include visible items - so ensure all layers/tracks you want exported are ticked.
Note2: For the Top Layer only, you can also go via the main Menu system - File-> Export All-> Single GPX File... 
Alternatively if you use the Export All-> GPX... it will ask for an export directory and then each TrackWaypoint layer will be saved individually.

HTH.

**Comment by rnorris** [comment]
Apologies for my misunderstanding.

So yes, ATM their is no way to do this within Viking. You have to use one of the Exports mentioned previously and then manually use GPSBabel separately.

It should be straight-forward to add an Agg Layer -> File -> Export with GPSBabel entry which would internally pass the 'Single GPX' result to GPSBabel.

**Comment by M-Reimer** [comment]
Actually what I planned to do is not possible with gpsbabel anyway: https://github.com/GPSBabel/gpsbabel/issues/1255
Maybe still useful in some cases to have, but does not solve the problem for me to easily export a format for web display.
