### ISSUE TITLE
Updating OSRM routing

### ISSUE THREAD

**Issue by ravl1084** [viking-gps/viking#24]
Hi,

I've put together a Python script to query OSRM and then produce a GPX out of the GeoJSON (<rant> who uses GeoJSON??</rant>) response.

I see that in the Viking preferences there is a dropdown to select a routing engine but only the default OSRM is available as a choice. Is there a way for me to add a new routing service?

**Comment by rnorris** [comment]
You can specify alternative routing engines via a configuration file ~/.viking/routing.xml
Hopefully the manual explains how to do this, with some lines like:

```
<objects>
  <!-- Note that OSRM no longer supports GPX output -->
  <object class="VikRoutingWebEngine">
    <property name="id">osrm</property>
    <property name="label">OSRM</property>
    <property name="format">geojson</property>
    <property name="url-base">http://router.project-osrm.org/viaroute?output=geojson</property>
    <property name="url-start-ll">&amp;loc=%s,%s</property>
    <property name="url-stop-ll">&amp;loc=%s,%s</property>
    <property name="url-via-ll">&amp;loc=%s,%s</property>
  </object>
</objects>

```

However you I don't think there's a way to run your program between Viking's request and the processing of the response, other than replacing the GPSBabel binary with your program

I note the *latest* (only in the source code git repository - so not in a release yet)  GPSBabel now has capability to read GeoJSON, so you may be better off investigating that.
When the 'format' property above is anything else than 'gpx', Viking will attempt to use GPSBabel to translate the result into GPX for Viking to use.

PS The last time I looked at OSRM I thought it returned it's own bespoke JSON schema, not GeoJSON, but I could be wrong.
NB Viking can load GeoJSON files if the program **togpx** (from https://www.npmjs.org/package/togpx) is available on the system, but only via Acquire->Import GeoJSON File... menu.

HTH

**Comment by ravl1084** [comment]
Thanks for the response! I tried GPSBabel 1.5.4 and I only get an empty GPX shell. While I was fiddling with the OSRM call, I did notice that the resulting JSON varies significantly depending on the parameters you pass, so it may not be pure GeoJSON. 
I think I'll just keep using my script as a separate utility and load the GPXs into Viking.

Thanks again.
