### ISSUE TITLE
Delete All toolbar icon lacks mouseover

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#240]
In your toolbar preferences, move the Delete all ("-") symbol into the toolbar.

Then a week later, use viking, not remembering what you did.

Because that "-" is the only (hope so) tool icon missing a mouseover, you can't tell what it does.

Package: viking                          
Version: 1.10-2+b1

**Comment by rnorris** [comment]
Good spot, thanks.
Reviewing the relevant code, there are few other more obscure commands that lack the tooltip - which I'll fix too - in due course.
