### ISSUE TITLE
Cannot create waypoints because creation menu extends beyond the screen

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#241]
On a chromebook the Create Waypoint dialog extends beyond the bottom of the screen and thus the OK button is not reachable with the mouse, so no waypoints can be created.

The menu cannot be moved, nor scrolled, nor resized, and totally assumes it will be fully visible to the user, which is not always the case.

That's a shame because the rest of viking works fine.

Yes, on a desktop there is plenty of room even beyond the bottom of that menu.

But on a chromebook the "Cancel" and "OK" buttons are just off the bottom of the screen inaccessible.

Package: viking                          
Version: 1.10-2+b1

P.S., even on desktop, the Cancel and OK buttons cover up the final "Source" entry textbox:
![20240122T220402](https://github.com/viking-gps/viking/assets/1230959/09292da3-57aa-45e2-83e7-fbcbc6038c97)

**Comment by jidanni** [comment]
Chromebook:
![Viking_waypoint_attempt](https://github.com/viking-gps/viking/assets/1230959/ca671ecc-68ed-4e37-bdc4-e338af50a637)
Also it seems the menu needn't be so vertically stacked, but perhaps was supposed to be a two column menu instead of the single column menu you see here.

**Comment by rnorris** [comment]
Agreed.
The Waypoint dialog has steadily been getting vertically bigger as more fields were added.
At least I split off some of the (assumed) lesser used options into an 'Extra' tab.

Either (or may both) - I'll look to make the dialog contents scrollable - and try to ensure the vertical size is never too big - this should be the easiest to implement.
And then perhaps change it to be a horizontal 'FieldName: Value'  pair layout. A bit more work to do this.
Previously I just followed the very original Viking version layout when extending this dialog.

I think the GTK3 theming (compared to GTK2) tends to insert more spacing around widgets exasperating any suboptimal layouts.

**Comment by rnorris** [comment]
![WaypointProperties](https://github.com/viking-gps/viking/assets/105411/8a7d0b62-4123-44b7-aca6-245d841a9984)

The new layout for Waypoint dialog, as shown for the Basic tab above - generally taking up less space - especially the vertical extents.
The Extra tab has a similar layout.
