### ISSUE TITLE
The ruler tool sometimes completely hangs Viking with 100% CPU time

### ISSUE THREAD

**Issue by vinc17fr** [viking-gps/viking#244]
After selecting the ruler tool and clicking on the map, Viking sometimes completely hangs with 100% CPU time taken in Cairo.

[Backtrace obtained with `gdb -p 655827`](https://github.com/viking-gps/viking/files/14157990/gdb.txt) (it is thread 1, i.e. LWP 655827, that takes the CPU time).

**Comment by vinc17fr** [comment]
Note: this is under Debian/unstable, using Viking 1.10 with the patch that fixes #202.

**Comment by rnorris** [comment]
I think this probably due to same underlying flaw as per #245, i.e. the fix in #175 should resolve it.
