### ISSUE TITLE
Sidebar zaps partially covered labels' background

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#247]
No big deal, but when the sidebar partially covers labels, it zaps their background (but oddly their foreground is unscathed.)

![white_labels_when_sidepanel](https://github.com/viking-gps/viking/assets/1230959/ea5a866f-cdf1-451c-be64-fb3202611dfd)
  
I.e., the white numbers are there, but their magenta background is gone.

**Comment by rnorris** [comment]
Agreed.
The purple background is the highlight for the selected item (individual item or entire layer).
There must a logic flaw in the drawing of the highlight, which is presumably not considering the text extents correctly.
e.g. Appears to be that as text starts outside the viewport bounds it doesn't perform the background highlight - but of course the extent of the text (and/or the actual point position) is in bounds. 
The highlight logic should match foreground text drawing logic.
