### ISSUE TITLE
Warn earlier I must be in UTM mode

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#256]
Viking "Generate directory of images" menu choice: warn me before I get into the dialog that I must be in UTM mode, not after. In fact grey-out that choice in the menu if I am not in UTM mode.

**Comment by rnorris** [comment]
Generally agreed.
However, I think I'll keep the menu entry 'active' - as otherwise it won't be so obvious (without reading an appropriately updated manual) what one would need to do to enable it.
