### ISSUE TITLE
Exit icon looks too much like side panel control

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#261]
![Screenshot 2024-04-28 08 53 06](https://github.com/viking-gps/viking/assets/1230959/d718d59c-56c1-41d2-a228-3ba80c7aa9b8)

Many times I have almost hit the exit button, thinking it controls (closing) the side panel.

In fact as you see here, it seems much more side panel related than the real side panel button, here at right.

In fact even some of these might be better choices for the exit button
- https://www.google.com/search?q=dead+bird+cartoon&udm=2
- https://www.google.com/search?q=dead+duck+cartoon&udm=2

> You can hide it via Customize (two fingers tap of trackpad in Chromebook)

And indeed that's what I did. But I'm just saying one day this is going to cause an accident. Even if there's sometimes an "are you sure?" dialog upon exit.

**Comment by rnorris** [comment]
These icons are as per the Desktop theme.
There are already multiple other standard ways to close the program - window bar [X], menu File->Exit and via short cut keys.
So I think it might be better just to remove the Exit button from the default toolbar.
