### ISSUE TITLE
New map layer should go on top by default

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#266]
In the manual we find

> Select Newly Created Layer
> A setting to control when a new layer is created that it is selected; otherwise the current selection is unchanged.

That might be all well and good, except what the user really certainly wants is the new map layer (created with CTRL+SHIFT+M) to be placed at the top of the stack, visible without further ado.

Or OK, I missed the word "map". I.e., "new layer" vs. "new map layer".  Anyway, I'm just talking about new map layers.

I mean it's like we bought a new car and we are eager to hop in the driver's seat. Or that old pair of shoes -- I even left them in the shoe store. Or they put my SIM card in the new phone at the store, and stuck the old phone in the box. Maybe I'll give it to the grandkids.

Or maybe add a Preference to control it.

Odd that one might want to select it, but not have it also on top. Or maybe new non-map layers already go on top.

(P.S., When I say "new map layer should go on top" I mean "on top of all the other map layers" not "on top of all layers.")

**Comment by rnorris** [comment]
As you say "new map layer should go on top of all the other map layers"

In principal it would be better if 'Map' (+DEMs, GeoRefs) layers were separated out into another layer/tree list; but that it is too large of a change to happen any time soon.

I think it should be possible to make adding new maps go above existing maps.
