### ISSUE TITLE
Molecular precision unnecessary in Webtools coordinate sharing

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#270]
In Tools > Webtools > OSM
https://www.openstreetmap.org/?lat=39.874057805453099&lon=-87.593172512904175&zoom=15

Perhaps molecular precision. Maybe some of it could be donated to https://github.com/viking-gps/viking/issues/234 ?! :-)

**Comment by rnorris** [comment]
I notice OSM now seems to use a precision related to the zoom level (either rounding off the unnecessary precision - or adding more 0s if necessary).
Nevertheless, passing on 6 decimal places for all web service usage should be adequate.
