### ISSUE TITLE
Add <referer> property

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#285]
Reading https://sourceforge.net/p/viking/wikiallura/Maps/ , one feels the lack of a `<referer>` field, as some sites will only serve tiles if the correct [HTTP referer](https://en.wikipedia.org/wiki/HTTP_referer) is set.

Wait, there is custom HTTP headers mention of the Viking man page (but not that wiki page.)

Wait, there is even a `referer` parameter mentioned on the man page.

**Comment by rnorris** [comment]
I've updated the Maps page to mention further configuration options are available.
