### ISSUE TITLE
--zoom often initially ignored

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#289]
Offline I do
```
$ viking -z 22 file.kml
```
but my -z is ignored.

Until I pan the screen etc.. Then it is suddenly obeyed.

Apparently viking is waiting for a certain tile. But we are offline. That tile is not coming.

Panning around etc. wakes viking up to this fact apparently, and then our -z is obeyed.

In fact it also happens sometimes online too, not only offline.

viking 1.10.

**Comment by Friptick** [comment]
Can confirm behavior.

**Comment by rnorris** [comment]
I have a fix in hand, Just need to find time to commit and upload. I'm busy ATM.

**Comment by Friptick** [comment]
Your project so take your time. Thanks for your work.
