### ISSUE TITLE
Selection disrupts layering

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#294]
If the user carefully layers their items,
![Screenshot 2024-08-02 09 30 25](https://github.com/user-attachments/assets/4ae51aa4-c510-4afd-8696-3b86425a294f)
Well, then that order shouldn't be disrupted simply due to selection,
![Screenshot 2024-08-02 09 30 42](https://github.com/user-attachments/assets/6a98b5c1-1257-4907-8b02-9a449e8c94fc)
Else the user is no longer left in full control. There is no way for them to keep that line below the label where it was. Viking 1.10.

**Comment by rnorris** [comment]
This is by design - that the selected item is drawn on top.

Consider having many tracks - which might cover the same paths/roads. Otherwise the selected item highlight may get obscured by other tracks.
