### ISSUE TITLE
Feature request: ability to plot extensions field in the gpx data

### ISSUE THREAD

**Issue by davidedelvento** [viking-gps/viking#31]
The gpx data sometimes contains extensions fields, such as the target pace a runner was trying to achieve (this is of course related to #26)
It would be nice to have this target pace in the same graph as the "speed" (pace) so that runners can compare how they did compared to their target.

**Comment by davidedelvento** [comment]
@rnorris wrote in #26 repeating here to keep the github issues more organized

> But I'd note a word of caution about the amount of effort required for 'plot extensions field in gpx data' since Viking doesn't handle really handle any extensions (i.e. fully supporting GPX 1.1). So I'd expect you need to create/extend the framework within Viking to handle such extensions and so your specific fields can be dealt with. Hopefully such a base would then lend itself for adding support for Heart Rate data etc... (see https://sourceforge.net/p/viking/feature-requests/96/ and https://sourceforge.net/p/viking/bugs/131/

**Comment by rnorris** [comment]
Can be more specific about which GPX extension fields you are alluding to and/or examples of such files?

I have not come across any extension schemas (or GPX files themselves) that have a target pace.

For pacing its relatively simple to eyeball the graphs if you are aiming for single pace throughout your run to see if you are above or below this target.
However I suspect you have a more complicated pacing strategy; how is this target pacing created to begin with anyway?

**Comment by davidedelvento** [comment]
I do not use anymore the running tracker which I used before, which was RunnerUp ([on Google play](https://play.google.com/store/apps/details?id=org.runnerup&hl=en_US) and available also [on github](https://github.com/jonasoreland/runnerup)). Therefore I cannot easily provide what you are asking, but you may be able to generate it yourself on your device, or programmatically with fake data by looking at its source code.

Instead, I use Garmin Connect which provides out-of-the-box the plotting functionality that I was asking (without me messing up with GPX files) as the screenshot below demonstrate. As you can see the target pace "comes and goes" with different durations and intensity levels. In fact, I do not use Viking anymore either, so if you are considering this just for me, you may well close the ticket. For runners, this is an essential features and its lack makes visualizing pace data pretty much useless, so you will want to consider implementing it if you want runners as Viking users, though.

![target_pace](https://user-images.githubusercontent.com/579771/84773229-58a09f00-af99-11ea-8168-88a565910bfc.png)

**Comment by rnorris** [comment]
I think this is out of scope for Viking since it is not specifically a fitness tracker.

Of course if someone was to implement this, I would certainly seek to include it.
