### ISSUE TITLE
Feature request: One-button hotkeys on tools

### ISSUE THREAD

**Issue by Shura0** [viking-gps/viking#40]
IT would be cool to have one-button hotkeys for tools selecting.
For example:
P for moving tool (now it's Ctrl+Shift+P)
Z for zoom (now it's Ctrl+Shift+Z)
etc...

**Comment by rnorris** [comment]
You can override the existing keybindings, this is covered in the manual (2.9 Keyboard Configuration).

> Keyboard configuration is supported by the standard GTK+ way of changing shortcuts for menu entries.
Hover over the menu option with the mouse pointer and press the keyboard shortcut you want to bind it to.
To delete a keyboard assignment, press Backspace whilst over the menu entry.

Note however that setting things like Tools->Pan to one button "p" (or even shift+P), means you can no longer use those characters when trying to type something in the left hand panel (e.g. to change the name of a track) as that keystroke is routed to the Tool Action.
I'm not sure if this is a bug or 'feature'.

Thus for single key use for tools you probably want to consider keys you'd be unlikely to type into layer names e.g. various punctuation or symbol characters such as: ` [ ]
