### ISSUE TITLE
Turn on automatic builds on Travis CI

### ISSUE THREAD

**Issue by krichter722** [viking-gps/viking#44]
Once the repository is activated on https://travis-ci.org (press `+` on the left, sync your account and activate) every commit and pull request is build automatically there.

**Comment by rnorris** [comment]
Travis CI is now activated.

For example see: https://travis-ci.org/rnorris/viking

**Comment by krichter722** [comment]
This is a fork of viking-gps/viking. Can someone turn on Travis CI for https://travis-ci.org/viking-gps/viking, please?!

**Comment by rnorris** [comment]
Done
