### ISSUE TITLE
GPX upload to OSM doesn't work anymore

### ISSUE THREAD

**Issue by mmd-osm** [viking-gps/viking#45]
Uploading GPX traces to OSM doesn't work anymore, as the curl command won't follow a redirect to HTTPS. https://github.com/viking-gps/viking/blob/master/src/osm-traces.c#L188 needs to be changed accordingly to use an "https://" address.

See https://github.com/openstreetmap/operations/issues/117 for details.

Error message:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://openstreetmap.org/api/0.6/gpx/create">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at www.openstreetmap.org Port 80</address>
</body></html>

** (viking:21792): WARNING **: failed to upload data: HTTP response is 301
```

**Comment by rnorris** [comment]
Thanks for raising this issue.
