### ISSUE TITLE
Shouldn't the NEWS file mention 1.6.2 too?

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#55]
Shouldn't the NEWS file mention 1.6.2 too?

**Comment by rnorris** [comment]
It does - the 1.6.2 is in separate branch from the main trunk (all the actual code changes should be in the trunk as well). The canonical version of the code is on SourceForge, with 1.6.Z at:

https://sourceforge.net/p/viking/code/ci/viking-1.6.z/tree/

Github is only a mirror of the trunk.

IIRC v1.6.1 hadn't diverged from the trunk, so the release numbering changes where made in trunk (perhaps this was not the cleanest approach).
Then 1.6.Z branch was created for applying any fixes into the 1.6 series (thus could make 1.6.3 etc...) if deemed necessary.

Perhaps when 1.7 is released, I'll remember to include the NEWS of the 1.6.2 changes too.

**Comment by jidanni** [comment]
Maybe warn all over the GitHub site that it is not just a mirror, but older, than SF.

**Comment by rnorris** [comment]
Version 1.7 has included the 1.6.2 changes too in the NEWS file
