### ISSUE TITLE
Sourceforge bug report method gone

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#56]
User tries to file proper bug report, but bug report link on
https://sourceforge.net/p/viking/wikiallura/Contribute/#bug-report
just gives "Whoops".

User will file bug reports on GitHub.

**Comment by jidanni** [comment]
OK I found https://sourceforge.net/p/viking/bugs/ .
Perhaps mention that on this GitHub.

**Comment by rnorris** [comment]
Wiki links on https://sourceforge.net/p/viking/wikiallura/Contribute have been updated.

Thanks for noticing.
