### ISSUE TITLE
Even changing alpha from 55 to 56 needs a licence review

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#57]
Even minor changes in alpha cause the licence screen to pop up upon save.
![df4](https://user-images.githubusercontent.com/1230959/45609903-838c5500-ba8c-11e8-879c-7fb673a66dff.jpg)

**Comment by jidanni** [comment]
We already saw it... many times.

**Comment by jidanni** [comment]
$ apt-cache policy $@
viking:
  Installed: 1.6.2-3+b2
  Candidate: 1.6.2-3+b2
  Version table:
 *** 1.6.2-3+b2 500
        500 http://opensource.nchc.org.tw/debian unstable/main amd64 Packages

**Comment by rnorris** [comment]
Progress this issue will be on SourceForge
