### ISSUE TITLE
Crash in the Windows version

### ISSUE THREAD

**Issue by marksev1** [viking-gps/viking#6]
Hello I've experienced constant crashing of Viking 1.6 in Windows 7 64-bit. While in Ubuntubit works fine. Is there maybe any more recent version I could try, if it is maybe more stable.

**Comment by rnorris** [comment]
At least two critical fixes are in the latest code.

https://sourceforge.net/p/viking/bugs/121/
https://sourceforge.net/p/viking/bugs/126/

They are race condition type bugs, so can happen on any system and with the timing aspect happen more on some peoples systems than others. Thus these are the most likely candidates.

I'm planning a on releasing a new version very soon, which of course will have a Windows build.

**Comment by marksev1** [comment]
Great, actually if I remember back they did occur also on one of my Ubuntu boxes. Looking forward to the new version! I'll report here if it fixed it for me.

**Comment by rnorris** [comment]
Have you had a chance to try the 1.6.1 release?

**Comment by marksev1** [comment]
Oh I wasn't yet aware it is out. Cool news, I'll try. I have to build from source right?

**Comment by rnorris** [comment]
The installer.bat is a script I use to generate the viking-X.Y.Z.0.exe file.

It shouldn't do much unless your system is set-up as per my emulated Windows development environment - and even then it shouldn't effect the system.

The installer is also on github here:
https://github.com/viking-gps/viking/releases/download/viking-1.6.1/viking-1.6.1.0.exe

I have access to 64bit Windows 7 machine - but I've not tried the 1.6.1 release it on (it has my own 1.6+ version on it - hence the 1.6.1 should work the same)

**Comment by marksev1** [comment]
Well the strange thing is that it didn't want to start even the older installer now (the 1.6), while an unrelated installer (Garmin Virbedit) it started fine. Really, really strange. And I tried restarting the pc, and even shutdown. Also another strange thing is that I can't kill the process from the task manager.
