### ISSUE TITLE
Geotag images does nothing when using KML files

### ISSUE THREAD

**Issue by rwesson** [viking-gps/viking#65]
I'm using v1.6, installed from the Linux Mint repositories. Regardless of what settings I apply when trying to use "Geotag images...", nothing happens. There is no indication of success or failure. I load a kml file, select a bunch of images with timestamps, click "OK", and nothing happens.

It's hard to tell if this is a bug or if I'm just doing something wrong. Would you be able to describe the expected behaviour and perhaps provide a working example?

**Comment by rwesson** [comment]
Thanks very much for this information! I'm probably not clear on the terminology but I have KML files that contain time information. And `exiftool` will tag the images directly from the KML file, eg `exiftool -geotag track.kml *.JPG` works perfectly. But if I convert the file with gpsbabel as you suggest, Viking will tag it. So I think it would be very useful for it to give an error message suggesting the user convert to GPX when they try to tag using a KML file, instead of the current case where nothing happens.

**Comment by rnorris** [comment]
I'm making progress on writing my own KML parser as part of #90 which would also address this issue; so I'm asking if it would be possible you could provide one of your KML files as an example, either attach it to here or if you prefer to email it directly to me - rw_norris at hotmail dot com - thanks.

**Comment by rwesson** [comment]
Here is one (renamed from .kml to .txt to allow it to be attached). As before, `exiftool -geotag` tagged the images correctly.
[BA630-20b98300.txt](https://github.com/viking-gps/viking/files/4628759/BA630-20b98300.txt)

**Comment by rnorris** [comment]
Thanks for that.
It appears this source KML file only has formal timestamps against the waypoints.
It contains time span descriptions for the lines (but these don't appear to be in a defined exchange schema format).

So I don't think my KML parser will help geotagging in this specific instance, so really Viking needs to automatically try against the waypoints (as I previously mentioned). Another job to go on to my TODO list.
