### ISSUE TITLE
Please adhere to file location standards and help us keep our home folders clean

### ISSUE THREAD

**Issue by alexander-gabriel** [viking-gps/viking#67]
Cluttering up a user's home folder isn't nice. Linux, Windows and Mac OS all have dedicated areas where programs can store data. Adhering to these allows us to manage our data more cleanly and keep our home folders free of clutter.

For Linux
Configuration location: $XDG_CONFIG_HOME/viking   (defaults to ~/.config/viking)
Cache location: $XDG_CACHE_HOME/viking      (defaults to ~/.cache/viking)
User data location: $XDG_DATA_HOME/viking    (defaults to ~/.local/share/viking)
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

For Mac OS
Library location: ~/Library/viking
App preferences location: ~/Library/Preferences/viking
Cache location: ~/Library/Caches/viking

**Comment by rnorris** [comment]
This has been a long time outstanding request. Please see:

https://sourceforge.net/p/viking/feature-requests/81/

**Comment by rnorris** [comment]
Code has been committed that addresses this issue.
