### ISSUE TITLE
Feature Requests: Viking Flatpak

### ISSUE THREAD

**Issue by g1ocke** [viking-gps/viking#70]
please create a flatpak on flathub.org
this promotes the dissemination of the software very much...

**Comment by gdt** [comment]
Perhaps you could file a request with that particular packaging system.  I don't see this as a job for the upstream packages.

**Comment by g1ocke** [comment]
I hope there is one, because Viking is very good

**Comment by rnorris** [comment]
I am pleased to annouce there is a Flatpak hosted on Flathub:

https://flathub.org/apps/details/org.viking.Viking

Currently this is Viking 1.8, but hopefully there will soon be a v1.9 - may be by the end of the year.

Note that as Flatpak sandbox, various system integration features no longer work properly:

1. Help does not work.
1. Print-Preview does not work.
1. Realtime tracking via GPSD does not work.
1. Export Layer --> 'Open with External Program', e.g. normally JOSM or Merkaator - does not work. 
1. Mapnik Layer (Map Creation) is disabled.

These don't work as they use GPSBabel which is not available in the Flathub flatpak.
1. File --> Acquire --> From GPS... ( or GPS Layer --> Download From GPS )
1. Import/Export of non built in file types
1. TrackWaypoint Filter functions
1. Serial device transfer

**Comment by rnorris** [comment]
Further note a separate flatpak build of Viking available as an individual flatpak file is made available here:

https://sourceforge.net/projects/viking/files/

This flatpak is built slightly different to the one on Flathub, as this one has gpsbabel built into the flatpak as well.
