### ISSUE TITLE
Brouter routing.xml

### ISSUE THREAD

**Issue by laudge** [viking-gps/viking#71]
default routing.xml for brouter is not working.

**Comment by rnorris** [comment]
It works on my Debian system for version 1.7.

Can you be more specific, which version?, what operating system?
Are there any error messages?

Can you run Viking in debug mode (as described in the manual) to capture more diagnostics.
i.e. on the command line:

    viking -dV

**Comment by laudge** [comment]
I am running Archlinux. Meanwhile, I found the solution : just need to copy routing.xml in ~/.viking/

**Comment by rnorris** [comment]
NB Viking reads files both from ~/.viking/ and also the 'system' ones, attempting to use each directory in $XDG_DATA_DIRS with /viking/ appended.
Thus typically for routing this will then resolve to including something like (for my Debian instance):

     /usr/share/viking/routing.xml

However I don't know where the Archlinux installs the routing.xml file

**Comment by infinitless** [comment]
I really can't get the routing to work! :(
