### ISSUE TITLE
How to install to desktop

### ISSUE THREAD

**Issue by Carruthers45** [viking-gps/viking#73]

**Comment by Carruthers45** [comment]
Installed Viking GPS via Snap, on Raspberry pi (Buster) it confirms installation is complete, I now require it to open in desktop, how do I do this, or find the information to allow me to do this?
kind regards

**Comment by rnorris** [comment]
Um, no idea.
Viking does not currently generate/support Snaps directly.
Please contact whomever created/provided the Snap for any support needed.
