### ISSUE TITLE
viking-1.8: error: ‘VIK_DEFAULT_ALTITUDE’ undeclared

### ISSUE THREAD

**Issue by targzeta** [viking-gps/viking#80]
Hi,
with `--with-libexif` I have this error:
```
geotag_exif.c:365:16: error: ‘VIK_DEFAULT_ALTITUDE’ undeclared (first use in this function)
```
I guess the problem was introduced by [this commit](https://github.com/viking-gps/viking/commit/808ea53b95d3e529622ebae4bd18265dde03bd7b).

Thank you in advance for your work!

Best regards,
Emanuele

**Comment by rnorris** [comment]
Thank you for the report.

A commit has been added to fix this issue.
