### ISSUE TITLE
Mapbox Outdoors map is not displayed

### ISSUE THREAD

**Issue by mkaehlcke** [viking-gps/viking#81]
I'm running Viking 1.7 on Debian 'Buster'. The default map is choice is 'Mapbox Outdoors', however the map isn't loaded/displayed. If I switch to a different map type (like OSM (Mapnik)) the map is displayed. I tried "Download Missing Onscreen Maps" and a few other things, but to no avail. The problem is persistent, I saw it consistently over a few months. Most of my activities are in the San Francisco Bay Area, I confirmed that 'Mapbox Outdoors' maps are generally available to this area.

**Comment by rnorris** [comment]
The Mapbox account (with the associated API token) used by Viking has been deactivated.

I'm unsure of the best way ahead for the default map.

Many tile services require access tokens and/or have usage restrictions.
(This is why OSM is not allowed to be the default anymore).

I don't think Viking would be allowed to use the API key used by gnome-maps.

In the mean time I'll probably make Blue Marble the default.

**Comment by rnorris** [comment]
OpenTopoMap now the default.

**Comment by tomboe311** [comment]
@rnorris How can I switch to OpenTopoMap?

I still get a download error for Mapbox @ OpenstreetMap.

Ubuntu 20.04.2 LTS
Viking 1.7

**Comment by rnorris** [comment]
@tomboe311 You can add additional maps to Viking via creating/editing your own ~/.viking/maps.xml file - this is covered in the Manual and in the Wiki - https://sourceforge.net/p/viking/wikiallura/Maps/

Try this for contents of your ~/.viking/maps.xml file:

    <objects>
      <object class="VikSlippyMapSource">
        <property name="name">OpenTopoMap</property>
        <property name="label">OpenTopoMap</property>
        <property name="hostname">a.tile.opentopomap.org</property>
        <property name="url">/%d/%d/%d.png</property>
        <property name="follow-location">2</property>
        <property name="copyright">Kartendaten: © OpenStreetMap-Mitwirkende, SRTM | Kartendarstellung: © OpenTopoMap</property>
        <property name="license">CC-BY-SA</property>
        <property name="license-url">https://creativecommons.org/licenses/by-sa/3.0/</property>
        <property name="id">901</property>
      </object>
    </objects>
