### ISSUE TITLE
Cache all tiles for a bounding box for later viewing offline

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#84]
Currently apparently the only way to cache an area of background OSM map so it will be still there later offline, is to pan around and zoom in and out while online.
It would be better if one could [sweep out a bounding box](https://www.offline-maps.net/en/help/maps/stored/store-area) and let Viking get all the tiles within, (to a zoom level we tell it) while we do something else.

**Comment by jidanni** [comment]
OK I suppose this is
> 8.2    Layer Operations
> 8.2.1    Download Missing Onscreen Maps
> This requests map tiles for areas of the viewport that do not currently have one.

**Comment by gdt** [comment]
Also, keep in mind that depending on the tile provider, viking has to be very careful about its behavior relative to the tile usage policy.

See the OSM policy at https://operations.osmfoundation.org/policies/tiles/
and in particular
```
downloading an area of over 250 tiles at zoom level 13 or higher for offline or later usage is forbidden
```

Probably viking should have code to enforce this rule.

**Comment by jidanni** [comment]
Naturally the user will exercise caution, just as when using
https://play.google.com/store/apps/details?id=net.psyberia.offlinemaps .

Anyway OK, I've cranked the cache to the max. 4 gigs or so. Now I would like to download some areas for offline use, without having to manually sweep along and zoom in and out while online.

**Comment by jidanni** [comment]
Actually the net.psyberia.offlinemaps app is programmed to not allow automatic downloads of Google tiles, so as not to violate a similar Google policy, so perhaps Viking could do the same. But then again how many sites actually welcome automatic downloading in the first place.

Hmmm, perhaps have a speed throttle...
