### ISSUE TITLE
Keyboard arrow keys should pan too

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#85]
The four arrow keys on the keyboard should also pan,
as an easier way than always having to use the mouse.

**Comment by rnorris** [comment]
At the moment there is global keyboard handler, but even trying to split that into a specific 'map' area vs other parts, the arrow keys tend to be intercepted and used by GTK itself for moving around all the menus / layerspanel - depending on which GUI bit has focus.
I'm not quite sure how some of these focus things work as the map part doesn't seem to retain the focus.

NB By default CTRL+Arrow Keys moves the maps; so you don't have to always use the mouse.

Also see #66.

**Comment by jidanni** [comment]
OK, but having to also hold CTRL is [no fun](https://stackoverflow.com/questions/45729047/disable-the-ctrl-scroll-to-zoom-google-maps). Anyway, perhaps bind them to do those CTRL+ actions, but without CTRL, as a best effort. Even if often competing with GTK... probably the user will remember to click in the main window to get them working again if not. Anyway, it is better than binding them to nothing as present.
