### ISSUE TITLE
Add "restore defaults" buttons in Preferences

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#86]
- Edit > Preferences > General needs a "restore defaults" button at bottom.
- Edit > Preferences > Startup needs a "restore defaults" button at bottom.
- ...

Yup, all of them need a "restore defaults" button at bottom.

In fact there also needs to be a master "restore defaults" button at the
bottom of just `Edit > Preferences` too.

**Comment by rnorris** [comment]
Agreed. This would be useful to add.

NB You can manually work around restoring all defaults by via removing your ~/.viking/viking.prefs file, since this is where they are kept. Or you could remove individual lines in that file as it is just plain text.
