### ISSUE TITLE
Map loads for a split second then goes gray again

### ISSUE THREAD

**Issue by marksev1** [viking-gps/viking#9]
Hi,

Viking 1.6.1 on W7-64-bit. Now it doesn't crash anymore, but the map just loads for a split second then everything goes gray and sometimes it even hangs.

**Comment by rnorris** [comment]
Not sure what could be causing this.
Perhaps taking a log of the debug output might help understand what's happening.

To do this on Windows, you need to run Viking from the command prompt and redirect the output to a file e.g.:

%ProgramFiles(x86)%\Viking.exe -Vd 2>&1 > %USERPROFILE%\viking.log

**Comment by marksev1** [comment]
I changed the paths for the Viking.exe and viking.log...but I'm getting a blank log file with no data inside. But when I run Viking like this, I got the gray "map" with a lot of small squares (like very miniature gray tiles).

**Comment by rnorris** [comment]
In this debug mode it draws a grid of black lines to represent the borders of the individual map tiles.

IIRC in Windows you need to close Viking, otherwise sometimes the log doesn't actually get flushed/written to disk.
