### ISSUE TITLE
OSM Transport map needs API key

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#91]
Choosing New Map Layer (Transport) has big "API Key Required" written all over map.

**Comment by rnorris** [comment]
You are invited to acquire your own API key and configure the maps resources appropriately to use your own key.

This is the price of using a free service.

The default OSM Transport API key is shared between all standard Viking users.
I'd consider it a bonus that one gets any tiles at all.

**Comment by rnorris** [comment]
NB There was previous discussion about this here:

https://sourceforge.net/p/viking/feature-requests/146/

**Comment by jidanni** [comment]
OK, but users will expect
- working entries
- placeholder empty entries

not also
- half working entries.

You can't blame them. No other viewer takes the approach that something, even half baked, is better than nothing.

I like that approach too. I'm just saying users will think it is unintentional... But there is no easy way to tell the user that indeed it is not Vikings's fault.

**Comment by jidanni** [comment]
All I know is every user who sees it thinks "Oh gosh. I better tell the Viking crew! They certainly are unaware of what is happening."

Therefore perhaps in the corner of the screen there should be a floating "i in a circle" that users could click and it would say that yes, indeed, they are aware. That's all that is needed.
