### ISSUE TITLE
Opentopomap uses ~/.viking-maps/Unknown .

### ISSUE THREAD

**Issue by jidanni** [viking-gps/viking#92]
New Map Layer (opentopomap) caches tiles in ~/.viking-maps/Unknown .
I bet that will clash with other Unknowns.
And whoever told it where to get the tiles, should also say where to cache them.

**Comment by jidanni** [comment]
Why doesn't it just use the same name as "Map Type", for the directory.

**Comment by rnorris** [comment]
There's a separate configuration value used for determining the tile directory (when using the OSM Cache Layout style).

Unfortunately there appears to be two errors here:
1. The default fallback all use 'Unknown', whereas it could use something derived from the map label. The label key has/should always been present.
2. The supplied system maps.xml doesn't have many "name" key entries and so they all use the same fallback. Lines missing such as:
>     <property name="name">OpenTopoMap</property>

As a workaround you can add appropriate "name" lines into the system installed maps.xml file. Typically this is located in /usr/share/viking or C:\Program Files\Viking\data

**Comment by jidanni** [comment]
I was going to blame http://gis.sinica.edu.tw/tileserver/viking.zip for not remembering to add name="name". But then even Viking's own doesn't always:
```
$ grep -c 'name="url"' /usr/share/doc/viking/examples/maps.xml
6
$ grep -c 'name="name"' /usr/share/doc/viking/examples/maps.xml
4
```

**Comment by jidanni** [comment]
Anyways, real life effects observed of mapping all to the same Unknown:
A weird _melange_ of different tiles from different maps.
