### ISSUE TITLE
GPS data is removed while geotagging

### ISSUE THREAD

**Issue by sandaihu** [viking-gps/viking#94]
Using viking 1.7 (same behaviour was noticed in 1.8), that while geotagging an image and choosing `Write EXIF`, it completely nukes unknown to viking GPS tags.

Before:
![2020-05-11_104513](https://user-images.githubusercontent.com/17235528/81544876-5cc51580-9378-11ea-92c6-3f16cd00e4b7.png)
After:
![2020-05-11_110813](https://user-images.githubusercontent.com/17235528/81544881-5df64280-9378-11ea-8f07-ea937c637cb0.png)

Including but not limited to `Exif.GPSInfo.GPSDateStamp` and `Exif.GPSInfo.GPSTimeStamp`.

The preferred behaviour would be to keep these in the Exif, to have the original GPS date in UTC stored.

Also it looks like that `geotag_exif.c:convert_to_entry()` at line 870 although is set to write version `2.2.0.0`, yet per above screenshot actually `2.0.0.0` is written.

Thanks and keep the good work.

**Comment by rnorris** [comment]
Can I inquire into your workflow?

Although I agree this is a bug (albeit more in the underlying library that is used to write the GPS information), I would like to understand why you would want to write GPS data when the image already has GPS information (unless the original values are wrong and you are attempting to correct them?).

Viking has the setting Geotag->Overwrite Existing GPS Information shown in the geotagging process to specifically to help accidentally writing EXIF values when they are already there.

Regarding geotag_exif.c:convert_to_entry() at line 870 although is set to write version 2.2.0.0,
this using [libexif](https://libexif.github.io/), whereas now Viking uses [gexiv2](https://wiki.gnome.org/Projects/gexiv2) by default.
ATM gexiv2 always sets the version to 2.0.0.0 (as part of its internals).
The change to gexiv2 was primarily to avoid data loss! Albeit more for it's support of XMP, see https://sourceforge.net/p/viking/bugs/112/

Potential use of libexif has been retained for build time support if specifically enabled (this was used on the Windows build, until using gexiv2 in the build process was supported).

**Comment by sandaihu** [comment]
Hi Rob, thanks for the reply. 

The images in question have been shot with a Samsung SM-J510FN (Samsung Galaxy J 2016) while the GPS is neither enabled on system level, nor while shooting the picture: so the image doesn't have any GPS tags at all - except the ones below - which I'd like to add via the geotagging and `Write Exif`.

It doesn't have any "real" GPS data, yet the phone always writes the following tags:
> [EXIF] GPSVersionID: 2.2.0.0
> [EXIF] GPSTimeStamp: 05:46:54
> [EXIF] GPSDateStamp: 2020:05:16

Which would be the correct UTC time, and would be useful to keep for later calculations ignoring all the timezone and DST adjustments in `Exif.Image.DateTimeOriginal`.
I also have a Nikon D200, that too writes an  `[EXIF] GPSVersionID: 2.2.0.0`  tag, which would be removed during geotagging.

Maybe this is a special side case, also I could run some post-processing to create or add back these 3 tags, but if it doesn't require major changes in the code I think these 3 tags should be always kept (if they exist).

I understand the case with the version numbers, thank you for the explanation.

**Comment by rnorris** [comment]
I have raised this issue with gexiv2 and await their response.

https://gitlab.gnome.org/GNOME/gexiv2/-/issues/53

It may be that using the convenience function of gexiv2_metadata_set_gps_info(), is not so useful after all, since that is causing the deletion of all the other GPS Info data. 

If that remains the behaviour of gexiv2_metadata_set_gps_info(), then instead Viking will need to manually set each individual exif gps tag as necessary, which should ensure any existing exif gps tags are unchanged.

**Comment by rnorris** [comment]
gexiv2 have released a new version that addresses this issue: gexiv2-0.12.1

Unfortunately they decided not to change the behaviour of the existing interface and have introduced a new function gexiv2_metadata_update_gps_info() which only updates the lat/lon/altitude values.

I think I'll fix Viking by making it use the new function if available (which is most likely), and then falling back to the current behaviour if not available.

**Comment by sandaihu** [comment]
> gexiv2_metadata_update_gps_info() which only updates the lat/lon/altitude values

Sounds good, looking forward to the new release.
