### ISSUE TITLE
Viking install via snap: Desktop file didn't specify exec field

### ISSUE THREAD

**Issue by amykyta3** [viking-gps/viking#95]
Installed for Ubuntu 18.04 via snap installer (https://snapcraft.io/viking-gps)

When I attempt to run it from the new desktop link, I get the following error:
![Screenshot from 2020-05-16 15-06-11](https://user-images.githubusercontent.com/12021539/82131143-ffb9cd00-9786-11ea-84cd-c5d064071b0b.png)

Confirmed that `/var/lib/snapd/desktop/applications/viking-gps_viking.desktop` indeed does not contain an `Exec` entry.

Fixed by adding the following to the `viking-gps_viking.desktop` file:
```
Exec=/snap/bin/viking-gps.viking
```

**Comment by rnorris** [comment]
Unfortunately at present Viking doesn't officially support snap.

The person whom created this snap: Rex Tsai (chihchun), has not engaged with the Viking project, so I am unable to assist.
